name: Update Instances List

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npx tsc main.ts && node main.js && rm -r main.js
    - name: Update List
      uses: int128/update-generated-files-action@v2
    
