on:
 pull_request:
 push:
  branches:
   - main
 schedule:
   - cron: "*/30 * * * *"
    
permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
      with:
         deno-version: vx.x.x
    - run: deno run main.ts
    - uses: int128/update-generated-files-action@v2
    
