name: Update Instances List
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npm i
    - run: npm run update
    - name: Update List
      uses: test-room-7/action-update-file@v1
      with:
       file-path: unified_instances.txt
       commit-msg: Update List
       github-token: ${{ secrets.GITHUB_TOKEN }}
