on:
 pull_request:
 push:
  branches:
   - main
 schedule:
   - cron: "*/30 * * * *"
    
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun main.ts
    - run: git add unified_instances.txt
    - run: git config user.email "action@github.com"
    - run: git config user.name "github-actions"
    - run: git commit -m $COMMIT_MESSAGE || true && git push || true
