name: Update Instances List

on:
 pull_request:
 push:
  branches:
   - main
 schedule:
   - cron: "*/30 * * * *"
    
permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun main.ts
    - uses: int128/update-generated-files-action@v2
    
