on:
 pull_request:
 push:
  branches:
   - main
 schedule:
   - cron: "*/10 * * * *"
    
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun updater.ts
    - run: git add dynamic_instances.json
    - run: git commit -m 'update'
    - run: git push
