name: Update Instances List

on:
  schedule:
    - cron: "*/30 * * * *"
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun main.ts
    - uses: int128/update-generated-files-action@v2
    
